Repository sailaja-adapa/Shresta, pull requests merged in 2025-02, with the labels that each got.

#48 Enhanced UI
  src/Setpass.jsx
  src/setpass.css
Labels: JWOC, medium

#45 Feature/solve navbar overlapping
  package.json
  src/Aboutus.jsx
  src/Navbar.jsx
  src/StoreImageTextFirebase.jsx
  src/hello.css
Labels: JWOC, hard

#67 dasboard design improved
  package-lock.json
  package.json
  postcss.config.mjs
  src/Dashboard.css
  src/Dashboard.jsx
  src/dashboard2.jpg
  src/index.css
Labels: JWOC

#58 location form
  README.md
  package-lock.json
  src/GetCurrentAddress.jsx
  src/Pass1.css
  src/WelcomePage.jsx
  src/otp2.jpg
  src/welcomepage.css
Labels: JWOC, hard
